# **Week 4 Binary Classifier**

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

In [62]:
# SGDClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

clf = SGDClassifier(max_iter=1000)
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))
print(X_train.shape)
print(X_test.shape)


0.9333333333333333
(120, 4)
(30, 4)


### **Confusion Matrix**


In [55]:
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0 11  1]
 [ 0  0  7]]


### Matrice

In [56]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# accuracy = accuracy_score(y_test, y_pred)
# precision = precision_score(y_test, y_pred, average=None)  # Per-class precision
# recall = recall_score(y_test, y_pred, average=None)  # Per-class recall
# f1 = f1_score(y_test, y_pred, average=None)  # Per-class F1-score

# print(f"Accuracy: {accuracy:.4f}")
# print(f"Precision: {precision}")
# print(f"Recall/Specificity: {recall}")
# print(f"F1-Score: {f1}")

print(classification_report(y_test, y_pred))

precision = precision_score(y_test, y_pred, average="macro")
recall = recall_score(y_test, y_pred, average="macro")
f1 = f1_score(y_test, y_pred, average="macro")
print(f"Macro Precision: {precision}, Macro Recall: {recall}, Macro F1: {f1}")


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        12
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

Macro Precision: 0.9583333333333334, Macro Recall: 0.9722222222222222, Macro F1: 0.9632850241545894
