In [3]:
from sklearn import datasets
iris = datasets.load_iris()


In [ ]:
# SGDClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

clf = SGDClassifier(max_iter=1000)
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))


0.8666666666666667


### **Confusion Matrix**


In [ ]:
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))

[[13  0  0]
 [ 4  1  4]
 [ 0  0  8]]


### Matrice

In [51]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# accuracy = accuracy_score(y_test, y_pred)
# precision = precision_score(y_test, y_pred, average=None)  # Per-class precision
# recall = recall_score(y_test, y_pred, average=None)  # Per-class recall
# f1 = f1_score(y_test, y_pred, average=None)  # Per-class F1-score

# print(f"Accuracy: {accuracy:.4f}")
# print(f"Precision: {precision}")
# print(f"Recall/Specificity: {recall}")
# print(f"F1-Score: {f1}")

print(classification_report(y_test, y_pred))

precision = precision_score(y_test, y_pred, average="macro")
recall = recall_score(y_test, y_pred, average="macro")
f1 = f1_score(y_test, y_pred, average="macro")
print(f"Macro Precision: {precision}, Macro Recall: {recall}, Macro F1: {f1}")


              precision    recall  f1-score   support

           0       0.35      0.55      0.43        11
           1       0.00      0.00      0.00        12
           2       0.33      0.57      0.42         7

    accuracy                           0.33        30
   macro avg       0.23      0.37      0.28        30
weighted avg       0.21      0.33      0.26        30

Macro Precision: 0.22875816993464052, Macro Recall: 0.3722943722943723, Macro F1: 0.2832080200501253
